### ISSUE TITLE
将应用安装到C盘以外时数据写入错误

### ISSUE THREAD

**Issue by cym104** [Teachoc/Bangumi#3]
Win 10 x64， 20H2，19042.330

**Comment by lhyzf** [comment]
请检查一下是不是最新版，以及提供更详细的错误信息。

**Comment by cym104** [comment]
windows显示版本号是 2.11.1.0
app内版本号是：v1.1.30 x64
错误信息是：“发生未知错误” 和 “参数错误”
![image](https://user-images.githubusercontent.com/32197077/85915141-9940c800-b877-11ea-8d13-c05f3499ab81.png)

**Comment by lhyzf** [comment]
试试重置应用后能否正常使用

**Comment by cym104** [comment]
试过了，重置应用倒是能打开app了，但那是因为bangumi-data选项在重置的过程中被关掉了。再打开bangumi-data选项还是会一样的报错。

**Comment by cym104** [comment]
试了一下，问题是出现在没有把app装在C盘的时候。如果app装在C盘就正常，但是安装的时候如果选择装到别的盘，或者装完以后在windows应用和功能界面把它移动到别的盘的话，就会出问题。

**Comment by lhyzf** [comment]
已修复，请等待应用商店更新。
