### ISSUE TITLE
登陆以后打开进度页面就会报错

### ISSUE THREAD

**Issue by cym104** [Teachoc/Bangumi#4]
“object reference not set to an instance of an object”

**Comment by lhyzf** [comment]
麻烦提供一下当前在看的番剧或 bangumi 的用户id

**Comment by cym104** [comment]
bangumi 的用户id同此处id

**Comment by lhyzf** [comment]
确认这个是用户名而不是昵称吗，我找不到你的主页

**Comment by cym104** [comment]
https://bgm.tv/anime/list/264151/do

**Comment by lhyzf** [comment]
错误原因为[《魔法纪录 魔法少女小圆外传 最终季》](https://bgm.tv/subject/339998)条目无图片造成进度页处理错误
