### ISSUE TITLE
[Feature request] 能不能加个选项来关闭修仙模式？

### ISSUE THREAD

**Issue by cym104** [Teachoc/Bangumi#5]
即不要把每天24点到27点的番组算在当天，而是算在第二天？这样能比较方便和BT站的时间表同步。
目前的进度时间表貌似是把每天0点到3点的番组算在前一天了。

**Comment by lhyzf** [comment]
应用在排序时根据日期和时间（这个受 bgm.tv 和 bangumi-data 影响）排序，不太清楚

> 不要把每天24点到27点的番组算在当天

是指什么样的情况，希望能举一些例子看一下。

**Comment by cym104** [comment]
> 应用在排序时根据日期和时间（这个受 bgm.tv 和 bangumi-data 影响）排序，不太清楚
> 
> > 不要把每天24点到27点的番组算在当天
> 
> 是指什么样的情况，希望能举一些例子看一下。

比如国王排名这个番，是周五的，但现在显示的是周四
或者无职转生，到有资源都是周一了，但现在显示的是周日。


==============
哦看来是bgm.tv上的信息就不准确

==============
哎等一下是不是时差问题？我发现有问题的好像多是日本时间23点播出的哎。
比如 86 -不存在的战区- 第二季

**Comment by lhyzf** [comment]
是时区问题，但是 bgm.tv 的时间只精确到日期，没法反推出正确的时间，在 bangumi-data 有提供放送时间的条目是优先使用 bangumi-data 的时间的，这个会更准确（可以给 [bangumi-data](https://github.com/bangumi-data/bangumi-data) 提 request 补全没及时更新的数据）。
