### ISSUE TITLE
对于漫画小说类的进度管理

### ISSUE THREAD

**Issue by lilyblessing** [Teachoc/Bangumi#7]
目前好像只支持动画三次元影视番剧等视频类进度管理，希望能支持漫画小说等书籍的进度管理。

**Comment by lhyzf** [comment]
我没有记录过书籍的进度，看了一下是可以同时使用 Chap. 和 Vol. 记录，两个记录互不影响的吗？

**Comment by lilyblessing** [comment]
> 我没有记录过书籍的进度，看了一下是可以同时使用 Chap. 和 Vol. 记录，两个记录互不影响的吗？

分别是连载的 XX话 和单行本的 XX卷 的记录，互不影响
